# MedMentions

## Preprocessed data

In [9]:
from src.data.data_loader import *

dataset_loader = DatasetLoader(dataset_name='ibm/MedMentions-ZS', source='huggingface', model_name='UFNLP/gatortron-base')
data_medmentions, classmap, umls_label_code, tokenizer = dataset_loader.load_dataset()

In [10]:
data_medmentions

DatasetDict({
    train: Dataset({
        features: ['tokens', 'ner_tags', 'token_labels', 'input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 26770
    })
    validation: Dataset({
        features: ['tokens', 'ner_tags', 'token_labels', 'input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 1289
    })
    test: Dataset({
        features: ['tokens', 'ner_tags', 'token_labels', 'input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 1048
    })
})

In [11]:
ind_example = 0
df = pd.DataFrame(columns=['tokens', 'ner_tags', 'token_labels', 'umls_semptype'])
df['tokens'] = data_medmentions['train'][ind_example]['tokens']
df['token_labels'] = data_medmentions['train'][ind_example]['token_labels']
df['ner_tags'] = data_medmentions['train'][ind_example]['ner_tags']
df['umls_label_code'] = [umls_label_code[code] for code in data_medmentions['train'][ind_example]['ner_tags']]
df.T

,0,1,2,3,4,5,6,7,8,9,10,11
tokens,DCTN4,as,a,modifier,of,chronic,Pseudomonas,aeruginosa,infection,in,cystic,fibrosis
ner_tags,B-T103,O,O,O,O,B-T038,I-T038,I-T038,I-T038,O,B-T038,I-T038
token_labels,32,42,42,42,42,14,15,15,15,42,14,15
umls_semptype,"[Chemicals & Drugs, Chemical]",None,None,None,None,"[Phenomena, Biologic Function]","[Phenomena, Biologic Function]","[Phenomena, Biologic Function]","[Phenomena, Biologic Function]",None,"[Phenomena, Biologic Function]","[Phenomena, Biologic Function]"

In [12]:
df = pd.DataFrame(columns=['input_ids', 'input', 'labels'])
df['input_ids'] = data_medmentions['train'][ind_example]['input_ids']
df['input'] = [tokenizer.decode([t]) for t in tokenizer.encode(' '.join(data_medmentions['train'][ind_example]['tokens']))]
df['labels'] = data_medmentions['train'][ind_example]['labels']
df.T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
input_ids,101,14348,50010,50014,50061,233,106,43059,154,1699,26169,17045,1632,145,9130,8805,102
input,[CLS],dc,##t,##n,##4,as,a,modifier,of,chronic,pseudomonas,aeruginosa,infection,in,cystic,fibrosis,[SEP]
labels,-100,32,-100,-100,-100,42,42,42,42,14,15,15,15,42,14,15,-100